/// The AWS::ApiGatewayV2::Route resource creates a route for an          API.
#[derive(Clone, Debug, Default, serde::Serialize)]
pub struct CfnRoute {
    ///
    /// The API identifier.
    ///
    /// Required: Yes
    ///
    /// Type: String
    ///
    /// Update requires: Replacement
    #[serde(rename = "ApiId")]
    pub api_id: String,

    ///
    /// Specifies whether an API key is required for the route. Supported only for WebSocket APIs.
    ///
    /// Required: No
    ///
    /// Type: Boolean
    ///
    /// Update requires: No interruption
    #[serde(rename = "ApiKeyRequired")]
    pub api_key_required: Option<bool>,

    ///
    /// The authorization scopes supported by this route.
    ///
    /// Required: No
    ///
    /// Type: List of String
    ///
    /// Update requires: No interruption
    #[serde(rename = "AuthorizationScopes")]
    pub authorization_scopes: Option<Vec<String>>,

    ///
    /// The authorization type for the route. For WebSocket APIs, valid values are        NONE for open access, AWS_IAM for using AWS IAM        permissions, and CUSTOM for using a Lambda        authorizer. For HTTP APIs, valid values are NONE for open access, JWT for using JSON Web Tokens, AWS_IAM for using AWS IAM         permissions, and CUSTOM for using a Lambda authorizer.
    ///
    /// Required: No
    ///
    /// Type: String
    ///
    /// Update requires: No interruption
    #[serde(rename = "AuthorizationType")]
    pub authorization_type: Option<String>,

    ///
    /// The identifier of the Authorizer resource to be associated with this route. The authorizer identifier is generated by API Gateway when you created the authorizer.
    ///
    /// Required: No
    ///
    /// Type: String
    ///
    /// Update requires: No interruption
    #[serde(rename = "AuthorizerId")]
    pub authorizer_id: Option<String>,

    ///
    /// The model selection expression for the route. Supported only for WebSocket APIs.
    ///
    /// Required: No
    ///
    /// Type: String
    ///
    /// Update requires: No interruption
    #[serde(rename = "ModelSelectionExpression")]
    pub model_selection_expression: Option<String>,

    ///
    /// The operation name for the route.
    ///
    /// Required: No
    ///
    /// Type: String
    ///
    /// Update requires: No interruption
    #[serde(rename = "OperationName")]
    pub operation_name: Option<String>,

    ///
    /// The request models for the route. Supported only for WebSocket APIs.
    ///
    /// Required: No
    ///
    /// Type: Json
    ///
    /// Update requires: No interruption
    #[serde(rename = "RequestModels")]
    pub request_models: Option<serde_json::Value>,

    ///
    /// The request parameters for the route. Supported only for WebSocket APIs.
    ///
    /// Required: No
    ///
    /// Type: Json
    ///
    /// Update requires: No interruption
    #[serde(rename = "RequestParameters")]
    pub request_parameters: Option<serde_json::Value>,

    ///
    /// The route key for the route. For HTTP APIs, the route key can be either $default, or a combination of an HTTP method and resource path, for example, GET /pets.
    ///
    /// Required: Yes
    ///
    /// Type: String
    ///
    /// Update requires: No interruption
    #[serde(rename = "RouteKey")]
    pub route_key: String,

    ///
    /// The route response selection expression for the route. Supported only for WebSocket APIs.
    ///
    /// Required: No
    ///
    /// Type: String
    ///
    /// Update requires: No interruption
    #[serde(rename = "RouteResponseSelectionExpression")]
    pub route_response_selection_expression: Option<String>,

    ///
    /// The target for the route.
    ///
    /// Required: No
    ///
    /// Type: String
    ///
    /// Update requires: No interruption
    #[serde(rename = "Target")]
    pub target: Option<String>,
}

impl cfn_resources::CfnResource for CfnRoute {
    fn type_string(&self) -> &'static str {
        "AWS::ApiGatewayV2::Route"
    }

    fn properties(&self) -> serde_json::Value {
        serde_json::to_value(self).expect("Failed to serialize to value")
    }

    fn validate(&self) -> Result<(), String> {
        Ok(())
    }
}
